### ISSUE TITLE
Windows release?

### ISSUE THREAD

**Issue by slrslr** [djey47/tdumt#3]
Hello, can You please add a Windows release so one can download it at https://github.com/djey47/tdumt/releases and just run or install on Windows?

I am only aware about v. 1.16.3 downloadable from https://turboduck.net/forums/topic/6702-djey-tdu-modding-tools-1163

**Comment by djey47** [comment]
Hi,

just created a release here. That's the same archive one could find via Turboduck or sharemods.

Regards.
